### ISSUE TITLE
Error creating tables

### ISSUE THREAD

**Issue by Himovic** [Himovic/NewWayFarma-Orders#1]
When i execute the project, there is an issue with creating tables. I configured the primary keys and foreign keys but there is only 3 tables created but the others no.

**Comment by mslowiak** [comment]
Configure H2 database for dev spring profile so I can run project and see what is the problem.
Actually you have credentials to mysql database with no access with actual credentials

**Comment by Himovic** [comment]
@mslowiak , sorry for my late response :) . I fixed the issue, the error was error_naming in sql. I was using key words as variables. Thank you :)
